import Score from '@/components/Score';
import '../Sass/main.scss'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Score/>
        {children}</body>
    </html>
  );
}
